### PR TITLE
Colours

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Are you in-principle interested in some form of arbitrary colouring like this? The inspiration is mostly from dstat, which colours output fields based on totally arbitrary boundaries which are usually useless but not distractingly or misleadingly harmful. The output is easier to read, IMO.

### CODE REVIEW

**Comment by siebenmann** [comment]
In theory I'm willing to take a well done change that adds colour support (provided that it defaults to off), but I have a lot of concerns about sensible, flexible implementation. Issues someone would need to think about:
- hardcoding ANSI is ugly; can one use terminfo/etc to get appropriate colour values?
- hardcoded thresholds are pretty much guaranteed to be wrong for some and perhaps many circumstances.
- the current patch is implemented only for one of the two mxiostat display modes.

**Comment by alexjurkiewicz** [comment]
- The only python lib that can get these codes is curses, which I don't think is suitable for the project. I could shell out, if you think that's preferable? (I could implement the hardcoded values in a `colors.red` class which might be prettier.)
- Agree. Three approaches are:
  - live with sometimes-wrong hardcoded thresholds
  - allow the user to specify thresholds
  - magical algorithm that learns appropriate thresholds after a few iterations. I'd like to just implement option #1 for now and leave space for #2 & #3 to be added in later.
- I didn't want to write an entire patch for something you might reject on principle :-)

**Comment by siebenmann** [comment]
The more I think about it, the more I think that I have both a micro and a macro issue with the current approach.

The micro issue is that I don't like how the code is structured now, particularly how it spreads colour all over much of the code. My gut is saying that a more appealing approach would be to have a single global 'colorizer' object that knows how to add color to various text strings (when given both the text string and necessary information about what it is). There'd be at least two implementations of the colorizer; one that does nothing, just returning the original string, and one that does ANSI colors. The colorizer then becomes the natural place to hook up things like different colour schemes and different priority thresholds and so on.

The macro issue is that I'd prefer to see this evolve separately before I try to merge it into the main code. Even beyond the code, I think it's clear that there's going to need to be a bunch of tuning and refining for things like thresholds, the right colors to use to be useful, how best to present it, and so on. Since I'm not going to use colours myself, this is not something that I can be more than a bystander for. My gut says that the best way to handle this is for you to maintain a longer-term 'colorized mxiostat' fork, working through these issues and evolving something that works well, and then when it's solid I'll pull the final result. I'd put a link to the colorized mxiostat in my mxiostat README so that interested people get directed to you.

Does this all make sense?

**Comment by alexjurkiewicz** [comment]
Yes, I agree on the micro point entirely. Your macro point is accepted.

I considered making a patchset to adapt mxiostat as a dstat plugin (which gives me the arbitrary colours), but I'm going to be a bit more ambitious and write my own *stat program to rule them all. I'll use mxiostat's core for disk IO monitoring, once I get to the point of usability. https://github.com/alexjurkiewicz/astat

Anyway, thanks for writing this code. It's replaced all my other tools for watching raw IO on our db servers.

**Pull request closed without merging**
