### PR TITLE
Add -i: display fields as integers

### PR DESCRIPTION
**Pull request by alexjurkiewicz**

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
I like this option because it keeps the decimal place aligned between rows.
Known issue: values <0.5 vanish with this option, which is not ideal. Printing "<0.5" in the case where 0 < field < 0.5 would be better, but I'm too lazy to implement that.

**Comment by siebenmann** [comment]
FYI: I'm not ignoring this, but I want to pull the code and see how I feel about it when I use it and I haven't had time to do that yet.

**Comment by alexjurkiewicz** [comment]
Poke. Also, doing this to the output is nice too: `mxiostat.py | sed -e 's/ 0 / - /g'`

**Comment by siebenmann** [comment]
I'm still contemplating how I want to handle the low-but-not-0 case. My current inclination is actually to take this as-is as a starting point then add additional options for things like '>0' and your sed version, because I can see at least potential uses for an 'all integers but they're all real numbers instead of funny characters' output option. Does this seem sane to you?

**Comment by alexjurkiewicz** [comment]
My opinions have changed a little.

I currently like using 0 for values <0.5 and - for 0. After you see both
values in output it is clear what each implies, and it fits my criteria for
being "more human readable".

Perhaps down the track this can be subsumed into a --format option for
greater control, but like you happy to cross that bridge at a later date.
On 29/11/2011 4:13 AM, "Chris Siebenmann" <
reply@reply.github.com>
wrote:

**Comment by alexjurkiewicz** [comment]
Poke.

**Comment by siebenmann** [comment]
After extensive delays, I'm going to take this as-is as a starting point for some sort of 'humane' output format version that can be done on top (which is where telling apart 0 and <0.5 can be done).

**Pull request merged**
